name: Daily job

on:
  push:
  schedule:
    # Every day at 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python gcinfo.py
